### ISSUE TITLE
 Something went wrong, please help

### ISSUE THREAD

**Issue by mayjack0312** [CoretechR/Keybon#10]
The bootloader has been flashed normally and the device has been recognized, but when programming the program, the output is: 
```
WARNING: library JC_Button claims to run on avr architecture(s) and may be incompatible with your current board which runs on STM32F1 architecture(s).
Sketch uses 36364 bytes (55%) of program storage space. Maximum is 65536 bytes.
Global variables use 6048 bytes (29%) of dynamic memory, leaving 14432 bytes for local variables. Maximum is 20480 bytes.
```
Moreover, the screen does not light up after programming, and the button settings do not respond.
![5640bb1f576de645fe4c3e70d27db45](https://github.com/CoretechR/Keybon/assets/102800660/9f0cd883-ed0f-4568-a3c4-647576230bc5)
![8675e9eda1c32b351214fd9dfa84dbf](https://github.com/CoretechR/Keybon/assets/102800660/6eaae0d0-fdf5-4e05-8ac9-a0e486eb923b)

**Comment by CoretechR** [comment]
Hi, there are a lot of weird dependencies and old libraries that this project uses. So it can be a little tricky to set up.
I just added a binary file that you can try to flash to your board:
https://github.com/CoretechR/Keybon/blob/main/keybon/keybon.ino.generic_stm32f103c.bin

**Comment by mayjack0312** [comment]
> Hi, there are a lot of weird dependencies and old libraries that this project uses. So it can be a little tricky to set up. I just added a binary file that you can try to flash to your board: https://github.com/CoretechR/Keybon/blob/main/keybon/keybon.ino.generic_stm32f103c.bin


I don’t know the technology well, so I hope you can help me. This project is really great. Thank you again for the firmware.

**Comment by mayjack0312** [comment]
> > Hi, there are a lot of weird dependencies and old libraries that this project uses. So it can be a little tricky to set up. I just added a binary file that you can try to flash to your board: https://github.com/CoretechR/Keybon/blob/main/keybon/keybon.ino.generic_stm32f103c.bin
> 
> I don’t know the technology well, so I hope you can help me. This project is really great. Thank you again for the firmware.

Please help me, it seems like I’ve fallen over again o(╥﹏╥)o
This time after flashing the firmware, the device can’t even read it.
![image](https://github.com/CoretechR/Keybon/assets/102800660/cb06cf2b-d304-4b23-9bd8-0bbf68b89499)

**Comment by CoretechR** [comment]
Did you manage to flash the binary file? 
In my experience, when Windows does not recognize the device, it was usually a hardware problem. Maybe you have a short on the PCB. You can also try to flash the bootloader again an see if that helps.

**Comment by mayjack0312** [comment]
> 您是否成功刷新了二进制文件？ 根据我的经验，当 Windows 无法识别该设备时，通常是硬件问题。可能是你的PCB短路了。您还可以尝试再次刷新引导加载程序，看看是否有帮助。

![image](https://github.com/CoretechR/Keybon/assets/102800660/3aca934e-e882-4dda-8ef8-875be2897587)

**Comment by mayjack0312** [comment]
Then I try to flash the boot now and it can’t be flashed (the flash loader tool is quite mysterious)
![image](https://github.com/CoretechR/Keybon/assets/102800660/f728c97f-4631-4e36-94e1-07968d6cfcef)

**Comment by CoretechR** [comment]
Yes, the flash loader does not always work on the first try. 
But if it does not work at all, I suspect a hardware issue. Please check your PCB, maybe there is something wrong with the wiring.

**Comment by mayjack0312** [comment]
> Yes, the flash loader does not always work on the first try.
But if it does not work at all, I suspect a hardware issue. Please check your PCB, maybe there is something wrong with the wiring.

Thank you for your patient answer. I basically spent all night working on the burning problem today.
![image](https://github.com/CoretechR/Keybon/assets/102800660/86fe907d-7d9e-43f0-8735-dededb018783)
I'm trying to use STM32CubeProgrammer directly for burning. So far, everything is good (I hope I can succeed this time)

However, there does seem to be some problems with directly flashing this firmware.
![image](https://github.com/CoretechR/Keybon/assets/102800660/00ec8099-5ae0-456e-bb9b-d3dae6d582fd)
This error message came out again

I tried uploading directly using arduino and this time I got a new error
```
WARNING: library JC_Button claims to run on avr architecture(s) and may be incompatible with your current board which runs on STM32F1 architecture(s).
Sketch uses 36364 bytes (55%) of program storage space. Maximum is 65536 bytes.
Global variables use 6048 bytes (29%) of dynamic memory, leaving 14432 bytes for local variables. Maximum is 20480 bytes.
maple_loader v0.1
Resetting to bootloader via DTR pulse
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000007110b5db, pid=28812, tid=22164
#
# JRE version: OpenJDK Runtime Environment Microsoft-40648 (11.0.16.1+1) (build 11.0.16.1+1-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-40648 (11.0.16.1+1-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [jSSC-2.8_x86_64.dll+0xb5db]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\LMY\AppData\Local\Arduino15\packages\stm32duino\tools\stm32tools\2022.9.26\win\hs_err_pid28812.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by mayjack0312** [comment]
This is the error log when uploading to arduino
[hs_err_pid28812.log](https://github.com/CoretechR/Keybon/files/13697397/hs_err_pid28812.log)

**Comment by CoretechR** [comment]
I have not worked with STM32CubeProgrammer before and don't know what is causing this error, sorry.

**Comment by mayjack0312** [comment]
> I have not worked with STM32CubeProgrammer before and don't know what is causing this error, sorry.


I searched online again and checked. The upload did not fail. The STM32CubeProgrammer burning should have been successful, but the screen did not light up and the function keys seemed to have no effect.

- [Screen](https://item.taobao.com/item.htm?spm=a1z09.2.0.0.67002e8dZrf75X&id=609013059005&_u=i3hq0fps6f57) I bought it here, 
I don’t know if it’s the reason for the mismatch.
