### ISSUE TITLE
dimensions needed

### ISSUE THREAD

**Issue by NoIDidntHackU** [CoretechR/Keybon#13]
what are the exact dimensions of the OLED screens? I want to make this myself, but cannot find a screen of the same product key where I live

**Comment by 4gordi** [comment]
Hi, where are you from? Is oled screen 64*48, 0.66 inch. 

I bought this one, for example:

https://shorturl.at/mCHSY

**Comment by NoIDidntHackU** [comment]
sorry, didnt see that anyone answered! i am from Australia, thank you for help
