### ISSUE TITLE
Button Library

### ISSUE THREAD

**Issue by koogar** [CoretechR/Keybon#2]
I had to rename the button library based on your link 
#include <JC_Button.h>  for it to compile.

Great project BTW :)

**Comment by gromain** [comment]
Also, you should be careful with the version of the library you used. The v2.0.0 release introduced a breaking change in the code https://github.com/JChristensen/JC_Button/releases/tag/2.0.0 .
If you don't want to do the following change, the latest version to use the original `Button.h` and its constructor is v1.0.1 .
Basically, you have to change the order of the parameters in the constructor of the Button.

It now looks like this:
```
Button button01(SW01, 5, true, true); //pin, debounce, pullup, invert
Button button02(SW02, 5, true, true); //pin, debounce, pullup, invert
Button button03(SW03, 5, true, true); //pin, debounce, pullup, invert
Button button04(SW04, 5, true, true); //pin, debounce, pullup, invert
Button button05(SW05, 5, true, true); //pin, debounce, pullup, invert
Button button06(SW06, 5, true, true); //pin, debounce, pullup, invert
Button button07(SW07, 5, true, true); //pin, debounce, pullup, invert
Button button08(SW08, 5, true, true); //pin, debounce, pullup, invert
Button button09(SW09, 5, true, true); //pin, debounce, pullup, invert
```

**Comment by gromain** [comment]
Also, you can add the following in `setup()`:
```
  button01.begin();
  button02.begin();
  button03.begin();
  button04.begin();
  button05.begin();
  button06.begin();
  button07.begin();
  button08.begin();
  button09.begin();
```

**Comment by koogar** [comment]
Thanks for the reply.

I just wanted to point it out as most people will just download whatever version is on the Github, unless told.

Cheers

Rupert
