### ISSUE TITLE
Gerber Files

### ISSUE THREAD

**Issue by asutrem** [CoretechR/Keybon#5]
When exporting the gerber files, the holes for the USB C port are not generated. How do I go about fixing this?

**Comment by CoretechR** [comment]
I am not an expert on EAGLE cam jobs. I successfully generated files using the settings that JLCPCB provides and the slots came out fine. The slots might not show up on the drill layer, there should be an additional layer for millings.

**Comment by asutrem** [comment]
Ok, I will check out the steps on jlcpcb when I order. thank you!
