### ISSUE TITLE
BOM Part Package Difference

### ISSUE THREAD

**Issue by gren236** [CoretechR/Keybon#6]
Hello! First of all - thank you for an amazing project!
I'm going to build one, but during the BOM list checking I've stumbled upon the difference of "C1,C2,C3" capacitors between the EAGLE board schema items list and the actual BOM inside this repo. `Keybon REV 1.1 BOM.csv` file has `0603` package defined for this capacitors, but in EAGLE schema they have `0805` package. What should I trust?

**Comment by CoretechR** [comment]
Hi, I usually only use 0603 components in my designs. But a few footprints are copy/pasted from other projects so some 0805 footprints might end up in the pcb. While I prefer 0603, these footprints can be populated with both 0603 and 0805.

**Comment by gren236** [comment]
Great, thanks! Gonna stick to 0805 then
