### ISSUE TITLE
Can't flash bootloader keybon.generic_stm32f103c

### ISSUE THREAD

**Issue by 4gordi** [CoretechR/Keybon#7]
Hi, everyone. I finished one keybon, and i have some problem. Firstly - after flash bootloader with keybon.generic_stm32f103c, i can't connect keybon to pc (windows 10), becouse error message usb device not recognized. But if i flash bootloader with generic_boot20_pc13 from rogerclarkmelbourne and remove the jumper boot0, keybon defined by the system as maple serial and i can flash arduino-hardware.
secondly - after flashing keybon.ino keyboard work fine, more precisely buttons, but screen work only second. Do you help me?

**Comment by CoretechR** [comment]
Hi, "generic_boot20_pc13" is the right bootloader. I should include that in the description. 
So only one of the 9 screens work? Have you double checked your solder connections? Can you maybe post a picture?
It is easy to short-circuit the flex connector if you are not careful.

**Comment by 4gordi** [comment]
Yes, second screen show picture, another screens don’t work. I can see short-circuit on x-ray machine

**Comment by 4gordi** [comment]
Maybe it’s problem becouse of i using wrong version of arduino ide or versions of libraries? I know button.h is outdated now.

**Comment by CoretechR** [comment]
You need version 1.7.5 of the Adafruit_GFX_Library. But I do not think that's the problem. The code should not even compile without the right version.

**Comment by 4gordi** [comment]
Adafruit_GFX_Library i’m use 1.7.5. When compiling, it displays an error related to button.h

**Comment by 4gordi** [comment]
![Uploading AAF0FF3B-0538-4930-ACB2-37BD0D4E2F0A.jpeg…]()

**Comment by 4gordi** [comment]
![5C0F54A9-AB0B-494E-AA96-D42B8867EB0E](https://user-images.githubusercontent.com/27728217/178636075-2c4f1c58-9f64-40a9-b607-3f95d9d06f2b.jpeg)

![29179626-7668-489A-9BD1-071F5A18693C](https://user-images.githubusercontent.com/27728217/178636120-09c7d269-fc67-48aa-b859-7810af57721a.jpeg)

![D25DD097-E1B5-400A-AB30-7ED8556539AF](https://user-images.githubusercontent.com/27728217/178636237-bdab318d-b33f-4357-9c3d-a1ded77ae10a.jpeg)

**Comment by CoretechR** [comment]
Those solder joints look perfect. An X-Ray is really a helpful tool. 
I would try to reduce the code to the minimum. Just initialise one display, make it solid white and then start with the second one that already works. Then you can change the code to another display and see if that does anything. This way you can also rule out any other library dependencies as you will only need the display libraries.

**Comment by 4gordi** [comment]
Thanx, i found my problem - bad PCB( Initially there was a problem with a 3.3 short to gnd, an underetched circuit board, and now there was no miso signal on all other screens except the second one. Sorry, before additional wire laying on miso, work perfect)
Recheck pcb after factory( But in code in keybon.ino need correct to string 

`#include <JC_Button.h>`

![Гифка с Gifius ru](https://user-images.githubusercontent.com/27728217/178701977-20b25a37-e663-4ee3-a742-95552003dfdd.gif)

**Comment by CoretechR** [comment]
That's great! Thanks for posting the photos. I will include the new button library in the description. It has been added to the Arduino ide for a long time, so there is no need to get it from GitHub anymore.
