### ISSUE TITLE
icon file

### ISSUE THREAD

**Issue by mayjack0312** [CoretechR/Keybon#9]
Please,can you provide its icon library file？

**Comment by CoretechR** [comment]
I added some bitmap examples:
https://github.com/CoretechR/Keybon/tree/main/keybon%20companion/bitmap%20examples
Sorry, that this took so long. I kind of forgot about the issue.

**Comment by mayjack0312** [comment]
> I added some bitmap examples: https://github.com/CoretechR/Keybon/tree/main/keybon%20companion/bitmap%20examples Sorry, that this took so long. I kind of forgot about the issue.

Thanks to the boss for providing the complete content. It is being reproduced recently, not too late, not too late at all.
